In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.random.rand(3, 2)

array([[0.74884826, 0.13361673],
       [0.64902934, 0.16535046],
       [0.98404499, 0.34580688]])

In [10]:
np.random.randn(3, 2)

array([[-0.22796009,  0.1933921 ],
       [ 0.68250145,  1.05118012],
       [ 1.19964356, -0.02137873]])

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
print(arr.shape)

(2, 3)


In [13]:
print(arr.ndim)

2


In [14]:
print(arr.size)

6


In [15]:
print(arr.dtype)

int64


In [16]:
import numpy as np
# Basic Math
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [17]:
print(a + b)
print(a * b)
print(np.sin(a))

[5 7 9]
[ 4 10 18]
[0.84147098 0.90929743 0.14112001]


In [18]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [19]:
print(np.dot(A, B))
print(A @ B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [20]:
# Aggregation
arr = np.array([1, 2, 3, 4])

In [21]:
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())

10
2.5
4
1
1.118033988749895
